server:
  port: 9092

spring:
  application:
    name: spring-zookeeper-webclient
  cloud:
    zookeeper:
      connect-string: localhost:2181
      dependencies:
        spring-zookeeper:
          path: /spring-zookeeper
          loadBalancerType: ROUND_ROBIN
          required: true
management:
  endpoints:
    web:
      exposure:
        include: health

remote:
  services:
    url: http://spring-zookeeper